## 实验一：Python基本语法实验

### 学号：202110304332；姓名：王鑫坡

### 一、实验目的
1. 掌握numpy模块中数组的定义，以及数组的相关操作。
2. 掌握Pandas模块中DataFrame数据结构的相关操作。

### 二、 实验内容

**题目1（10分）：**  
简述numpy模块中的数组、Pandas模块中的Series和DataFrame数据结构各自的特点，以及他们与Python自带的列表、元组、字典等数据类型的区别。

**答：**  
(一)	NumPy数组和Python列表的区别：
1.	NumPy数组可以容纳同一数据类型的元素，而Python列表可以容纳不同类型的元素。
2.	NumPy数组支持向量化操作，使得对数组的操作可以在整个数组上进行，而不需要使用显式循环，从而提高了计算效率。
3.	NumPy数组支持广播（Broadcasting）功能，可以对形状不同的数组进行算术运算，使得编写代码更加简洁。
4.	NumPy数组占用的内存比Python列表更少，因为NumPy数组中的元素占用的空间更小。
(二)	Pandas中的Series和DataFrame与NumPy数组的区别：
1.	Series是一维的数据结构，类似于Python的字典，其中包含索引和数据，而DataFrame是二维的数据结构，类似于电子表格，由多个Series组成。
2.	Series和DataFrame可以容纳不同类型的元素，但是由于Pandas是基于NumPy开发的，因此它们在性能和效率方面具有NumPy的特点。
3.	Series和DataFrame具有许多内置的方法和功能，使得数据分析和处理变得更加简单和高效。
4.	Series和DataFrame可以对缺失的数据进行处理，提供了灵活的处理方式。
(三)	与Python自带的列表、元组、字典等数据类型的区别：
1.	列表可以容纳不同类型的元素，而NumPy数组和Pandas的Series和DataFrame只能容纳同一类型的元素。
2.	列表、元组和字典不支持向量化操作，而NumPy数组和Pandas的Series和DataFrame支持向量化操作。
3.	列表和元组是不可变的，而NumPy数组和Pandas的Series和DataFrame是可变的。
4.	字典是由键和值组成的，而Pandas的Series是由索引和值组成的。DataFrame是由多个Series组成，可以看作是由多个字典组成的。

**题目2（25分）：**  
编写程序，采用numpy模块中的随机数生成函数（随机数的种子数设置为10）创建一个数字大小范围为0~100，形状为（10，10）的二维数组 myarr1，然后对数组myarr1进行以下操作：  
（1）获取数组myarr1前5行的数据并输出；  
（2）从数组myarr1的第1行开始到第7行，步长为2进行切片，并输出切片后的结果；  
（3）获取数组myarr1第3行和第7行中，第2到第6列的数据并输出；  
（4）将数组myarr1纵向拆分成两部分，上半部分为数组myarr1的前4行，下半部分为数组myarr1的最后6行；  
（5）将数组myarr1转换为形状为（5，20）的数组，并输出转换后的结果。

In [20]:
# 题目2
import numpy as np

# 设置随机数种子数为 10，生成形状为 (10, 10) 的二维数组 myarr1
np.random.seed(10)
myarr1 = np.random.randint(0, 100, (10, 10))

# 获取数组 myarr1 的前 5 行的数据并输出
print("前 5 行数据：")
display(myarr1[:5])

# 对数组 myarr1 进行切片，从第 1 行开始到第 7 行，步长为 2，并输出切片后的结果
print("切片后的结果：")
display(myarr1[0:8:2])

# 获取数组 myarr1 第 3 行和第 7 行中，第 2 到第 6 列的数据并输出
print("第 3 行和第 7 行，第 2 到第 6 列的数据：")
display(myarr1[[2, 7]][:, 1:6])

# 将数组 myarr1 纵向拆分成两部分，上半部分为数组 myarr1 的前 4 行，下半部分为数组 myarr1 的最后 6 行
myarr1_split = np.vsplit(myarr1, [4])

# 输出拆分后的结果
print("拆分后的结果：")
display(myarr1_split)

# 将数组 myarr1 转换为形状为 (5, 20) 的数组，并输出转换后的结果
myarr1_reshaped = np.reshape(myarr1, (5, 20))
print("转换后的结果：")
display(myarr1_reshaped)

前 5 行数据：


array([[ 9, 15, 64, 28, 89, 93, 29,  8, 73,  0],
       [40, 36, 16, 11, 54, 88, 62, 33, 72, 78],
       [49, 51, 54, 77, 69, 13, 25, 13, 92, 86],
       [30, 30, 89, 12, 65, 31, 57, 36, 27, 18],
       [93, 77, 22, 23, 94, 11, 28, 74, 88,  9]])

切片后的结果：


array([[ 9, 15, 64, 28, 89, 93, 29,  8, 73,  0],
       [49, 51, 54, 77, 69, 13, 25, 13, 92, 86],
       [93, 77, 22, 23, 94, 11, 28, 74, 88,  9],
       [28, 33, 84, 96, 88, 44,  5,  4, 71, 88]])

第 3 行和第 7 行，第 2 到第 6 列的数据：


array([[51, 54, 77, 69, 13],
       [50, 54, 34, 15, 77]])

拆分后的结果：


[array([[ 9, 15, 64, 28, 89, 93, 29,  8, 73,  0],
        [40, 36, 16, 11, 54, 88, 62, 33, 72, 78],
        [49, 51, 54, 77, 69, 13, 25, 13, 92, 86],
        [30, 30, 89, 12, 65, 31, 57, 36, 27, 18]]),
 array([[93, 77, 22, 23, 94, 11, 28, 74, 88,  9],
        [15, 18, 80, 71, 88, 11, 17, 46,  7, 75],
        [28, 33, 84, 96, 88, 44,  5,  4, 71, 88],
        [88, 50, 54, 34, 15, 77, 88, 15,  6, 85],
        [22, 11, 12, 92, 96, 62, 57, 79, 42, 57],
        [97, 50, 45, 40, 89, 73, 37,  0, 18, 23]])]

转换后的结果：


array([[ 9, 15, 64, 28, 89, 93, 29,  8, 73,  0, 40, 36, 16, 11, 54, 88,
        62, 33, 72, 78],
       [49, 51, 54, 77, 69, 13, 25, 13, 92, 86, 30, 30, 89, 12, 65, 31,
        57, 36, 27, 18],
       [93, 77, 22, 23, 94, 11, 28, 74, 88,  9, 15, 18, 80, 71, 88, 11,
        17, 46,  7, 75],
       [28, 33, 84, 96, 88, 44,  5,  4, 71, 88, 88, 50, 54, 34, 15, 77,
        88, 15,  6, 85],
       [22, 11, 12, 92, 96, 62, 57, 79, 42, 57, 97, 50, 45, 40, 89, 73,
        37,  0, 18, 23]])

**题目3（25分）：**  
假设有一组鸢尾花花瓣长度的数据：1.0, 2.1, 1.2, 3.3, 2.4, 1.5, 4.6, 5.7, 1.9, 3.0, 3.3, 4.5, 3.7, 3.4, 3.8, 3.9, 4.1, 4.2, 6.0, 3.1, 6.3。  
编写程序，采用numpy模块中的相关函数对这组数据进行排序，并求出和、累积和、均值、标准差、方差、最小值、最大值。  
要求输出这些结果，输出时要有相应的提示性语句（例如：print("这组鸢尾花花瓣长度数据的均值为：", meanvalue)）。

In [21]:
# 题目3
import numpy as np

# 定义鸢尾花花瓣长度数据
data = np.array([1.0, 2.1, 1.2, 3.3, 2.4, 1.5, 4.6, 5.7, 1.9, 3.0, 3.3, 4.5, 3.7, 3.4, 3.8, 3.9, 4.1, 4.2, 6.0, 3.1, 6.3])

# 对数据进行排序
sorted_data = np.sort(data)

# 求和
sum_value = np.sum(sorted_data)

# 累积和
cumulative_sum = np.cumsum(sorted_data)

# 均值
mean_value = np.mean(sorted_data)

# 标准差
std_value = np.std(sorted_data)

# 方差
var_value = np.var(sorted_data)

# 最小值
min_value = np.min(sorted_data)

# 最大值
max_value = np.max(sorted_data)

# 输出结果
print("排序后的数据为：", sorted_data)
print("这组鸢尾花花瓣长度数据的和为：", sum_value)
print("这组鸢尾花花瓣长度数据的累积和为：", cumulative_sum)
print("这组鸢尾花花瓣长度数据的均值为：", mean_value)
print("这组鸢尾花花瓣长度数据的标准差为：", std_value)
print("这组鸢尾花花瓣长度数据的方差为：", var_value)
print("这组鸢尾花花瓣长度数据的最小值为：", min_value)
print("这组鸢尾花花瓣长度数据的最大值为：", max_value)

'排序后的数据为：'

array([1. , 1.2, 1.5, 1.9, 2.1, 2.4, 3. , 3.1, 3.3, 3.3, 3.4, 3.7, 3.8,
       3.9, 4.1, 4.2, 4.5, 4.6, 5.7, 6. , 6.3])

'这组鸢尾花花瓣长度数据的和为：'

73.00000000000001

'这组鸢尾花花瓣长度数据的累积和为：'

array([ 1. ,  2.2,  3.7,  5.6,  7.7, 10.1, 13.1, 16.2, 19.5, 22.8, 26.2,
       29.9, 33.7, 37.6, 41.7, 45.9, 50.4, 55. , 60.7, 66.7, 73. ])

'这组鸢尾花花瓣长度数据的均值为：'

3.4761904761904767

'这组鸢尾花花瓣长度数据的标准差为：'

1.4481202139998637

'这组鸢尾花花瓣长度数据的方差为：'

2.097052154195011

'这组鸢尾花花瓣长度数据的最小值为：'

1.0

'这组鸢尾花花瓣长度数据的最大值为：'

6.3

**题目4（40分）：**  
使用Pandas模块加载测试数据“testDataE1.xlsx”，然后对该数据完成以下操作：  
（1）加载数据“testDataE1.xlsx”，并显示该数据的前10行；  
（2）用方法describe()查看该数据框的描述性统计；  
（3）查看该数据框的形状；  
（4）采用显式index读取“白细胞计数”这一列的前5行；  
（5）提取第30至45行中“淋巴细胞计数”和“血小板计数”这两列的数据；  
（6）提取第2至6列的所有行数据；  
（7）对该数据按“血小板计数”这一列进行降序排序；  
（8）利用groupby()函数进行分组统计：以“性别”作为分组依据或条件；分组后统计“白细胞计数”的平均值、最大值、中值、最小值。

In [22]:
# 题目4
import pandas as pd
pd.set_option('display.max_rows', None)  # 显示所有行
pd.set_option('display.max_columns', None)  # 显示所有列
# (1) 加载数据并显示前10行
df = pd.read_excel('testDataE1.xlsx')
display(df.head(10))

# (2) 用方法describe()查看该数据框的描述性统计
display(df.describe())

# (3) 查看该数据框的形状
display(df.shape)

# (4) 采用显式index读取“白细胞计数”这一列的前5行
display(df.loc[0:4, '白细胞计数'])

# (5) 提取第30至45行中“淋巴细胞计数”和“血小板计数”这两列的数据
display(df.loc[29:45, ['淋巴细胞计数', '血小板计数']])

# (6) 提取第2至6列的所有行数据
display(df.iloc[:, 1:6])

# (7) 对该数据按“血小板计数”这一列进行降序排序
display(df.sort_values(by='血小板计数', ascending=False))

# (8) 利用groupby()函数进行分组统计
grouped = df.groupby('性别')['白细胞计数']
display(grouped.agg(['mean', 'max', 'median', 'min']))

序号  性别            身份证号 是否吸烟 是否饮酒 开始从事某工作年份  体检年份  淋巴细胞计数  白细胞计数  血小板计数
0    1  女  ****1982080000    否    否     2009年  2017     2.4    8.5    248
1    2  女  ****1984110000    否    否     2015年  2017     1.8    5.8    300
2    3  男  ****1983060000    否    否     2013年  2017     2.0    5.6    195
3    4  男  ****1985040000    否    否     2014年  2017     2.5    6.6    252
4    5  男  ****1986040000    否    否     2014年  2017     1.3    5.2    169
5    6  男  ****1982040000    否    否     2011年  2017     1.6    5.2    165
6    7  男  ****1988010000    否    否     2015年  2017     1.0    4.3    110
7    8  男  ****1960060000    否    否     1982年  2017     1.9    5.5    100
8    9  男  ****1964050000    否    否     1984年  2017     2.1    5.3    272
9   10  男  ****1987030000    否    否     2010年  2017     1.6    5.0    253

序号          体检年份      淋巴细胞计数       白细胞计数       血小板计数
count  142.000000   142.000000  142.000000  142.000000  142.000000
mean    71.500000  2016.704225    1.790845    8.443662  195.760563
std     41.135953     0.712490    0.468271   33.459677   55.387344
min      1.000000  2015.000000    1.000000    3.200000   86.000000
25%     36.250000  2017.000000    1.500000    4.700000  159.500000
50%     71.500000  2017.000000    1.700000    5.350000  198.000000
75%    106.750000  2017.000000    2.075000    6.200000  235.250000
max    142.000000  2017.000000    3.200000  404.000000  347.000000

(142, 10)

0    8.5
1    5.8
2    5.6
3    6.6
4    5.2
Name: 白细胞计数, dtype: float64

淋巴细胞计数  血小板计数
29     1.3    227
30     2.0    310
31     1.3    166
32     1.5    228
33     1.8    206
34     3.0    204
35     1.5    251
36     2.6    208
37     1.2    101
38     1.7    238
39     2.1    195
40     1.5    177
41     1.6    233
42     1.9    121
43     1.3    190
44     1.5    162
45     1.5    204

性别            身份证号 是否吸烟 是否饮酒 开始从事某工作年份
0    女  ****1982080000    否    否     2009年
1    女  ****1984110000    否    否     2015年
2    男  ****1983060000    否    否     2013年
3    男  ****1985040000    否    否     2014年
4    男  ****1986040000    否    否     2014年
5    男  ****1982040000    否    否     2011年
6    男  ****1988010000    否    否     2015年
7    男  ****1960060000    否    否     1982年
8    男  ****1964050000    否    否     1984年
9    男  ****1987030000    否    否     2010年
10   男  ****1982100000    否    否     2012年
11   男  ****1973040000    否    否     1992年
12   女  ****1985060000    否    否     2012年
13   女  ****1985120000    否    否     2013年
14   女  ****1985110000    否    否     2014年
15   男  ****1972110000    否    否     1996年
16   女  ****1972110000    否    否     2015年
17   男  ****1198000000    否    否     2009年
18   男  ****1978030000    否    否     2001年
19   男  ****1979080000    否    否     1998年
20   男  ****1979080000    否    否     2014年
21   女  ****1991110000    否    否     2014年
22   男  ****1973060000    否    是     1999年
23   女  ****1981090000    否    否     1999年
24   女  ****1975110000    否    否     1994年
25   女  ****1990020000    否    否     2012年
26   女  ****1981120000    否    否     2009年
27   女  ****1990070000    否    否     2010年
28   女  ****1963120000    否    否     2011年
29   女  ****1984020000    否    否     2003年
30   女  ****1978090000    否    否     1997年
31   女  ****1985060000    否    否     2006年
32   男  ****1993090000    是    否     2015年
33   女  ****1983040000    否    否     2015年
34   男  ****1989110000    否    否     2012年
35   男  ****1976110000    否    否     1996年
36   男  ****1984100000    否    否     2013年
37   男  ****1947010000    否    否     1970年
38   男  ****1989080000    否    否     2011年
39   女  ****1992020000    否    否     2010年
40   女  ****1985080000    否    否     2015年
41   男  ****1992100000    否    否     2015年
42   女  ****1987090000    否    否     2010年
43   女  ****1985030000    否    否     2006年
44   女  ****1982080000    否    否     2012年
45   女  ****1982020000    否    否     2009年
46   女  ****1964010000    否    否     1987年
47   女  ****1984090000    否    否     2010年
48   男  ****1971050000    否    否     2008年
49   男  ****1978010000    否    否     2003年
50   男  ****1988090000    否    否     2016年
51   男  ****1988010000    否    否     2015年
52   男  ****1974060000    否    否     2005年
53   女  ****1986030000    否    否     2015年
54   男  ****1988100000    否    否     2015年
55   男  ****1988100000    否    否     2015年
56   男  ****1978050000    否    否     1998年
57   男  ****1987000000    否    否     2009年
58   女  ****1983120000    否    否     2003年
59   男  ****1951090000    否    否     1974年
60   女  ****1975100000    否    否     2010年
61   男  ****1982090000    否    否     2007年
62   男  ****1981120000    否    否     2004年
63   男  ****1984050000    否    否     2009年
64   男  ****1987020000    否    否     2014年
65   女  ****1985050000    否    否     2011年
66   女  ****1991030000    否    否     2015年
67   女  ****1985060000    否    否     2009年
68   男  ****1958090000    否    否     1976年
69   男  ****1981100000    否    否     2007年
70   男  ****1983030000    否    否     2005年
71   男  ****1991090000    否    否     2015年
72   女  ****1985010000    否    否     2009年
73   女  ****1981020000    否    否     2008年
74   女  ****1982040000    否    否     2011年
75   男  ****1985120000    否    否     2006年
76   女  ****1988020000    否    否     2009年
77   男  ****1980040000    否    否     2005年
78   女  ****1971080000    否    否     2007年
79   女  ****1971080000    否    否     2007年
80   女  ****1971010000    否    否     1995年
81   男  ****1978110000    否    否     2014年
82   男  ****1993070000    否    否     2015年
83   男  ****1992040000    否    否     2015年
84   男  ****1992040000    否    否     2015年
85   男  ****1986080000    否    否     2016年
86   男  ****1986080000    否    否     2016年
87   男  ****1986080000    否    否     2016年
88   男  ****1984030000    否    否     2016年
89   女  ****1985010000    否    否     2016年
90   女  ****1976040000    否    否     2007年
91   女  ****1976040000    否    否     2007年
92   

序号  性别            身份证号 是否吸烟 是否饮酒 开始从事某工作年份  体检年份  淋巴细胞计数  白细胞计数  血小板计数
116  117  男  ****1994110000    否    否     2015年  2017     2.2    9.2    347
115  116  男  ****1994110000    否    否     2015年  2017     2.2    9.2    347
67    68  女  ****1985060000    否    否     2009年  2017     2.6    7.2    322
30    31  女  ****1978090000    否    否     1997年  2017     2.0    6.1    310
1      2  女  ****1984110000    否    否     2015年  2017     1.8    5.8    300
128  129  男  ****1992010000    否    否     2014年  2015     1.9    4.1    290
25    26  女  ****1990020000    否    否     2012年  2017     2.0    5.2    280
84    85  男  ****1992040000    否    否     2015年  2017     2.0    5.5    280
83    84  男  ****1992040000    否    否     2015年  2017     2.0    5.5    280
8      9  男  ****1964050000    否    否     1984年  2017     2.1    5.3    272
91    92  女  ****1976040000    否    否     2007年  2017     1.1    4.9    269
90    91  女  ****1976040000    否    否     2007年  2017     1.1    4.9    269
23    24  女  ****1981090000    否    否     1999年  2017     1.5    4.8    267
60    61  女  ****1975100000    否    否     2010年  2017     1.5    5.0    261
55    56  男  ****1988100000    否    否     2015年  2017     2.2    5.6    258
54    55  男  ****1988100000    否    否     2015年  2017     2.2    5.6    258
52    53  男  ****1974060000    否    否     2005年  2017     2.5    6.1    256
140  141  女  ****1995010000    否    否     2014年  2015     1.5    7.5    255
19    20  男  ****1979080000    否    否     1998年  2017     2.5    6.1    255
64    65  男  ****1987020000    否    否     2014年  2017     1.8    5.0    254
9     10  男  ****1987030000    否    否     2010年  2017     1.6    5.0    253
3      4  男  ****1985040000    否    否     2014年  2017     2.5    6.6    252
35    36  男  ****1976110000    否    否     1996年  2017     1.5    4.5    251
100  101  男  ****1993100000    否    否     2012年  2017     1.5    4.9    251
0      1  女  ****1982080000    否    否     2009年  2017     2.4    8.5    248
18    19  男  ****1978030000    否    否     2001年  2017     3.2    7.7    248
22    23  男  ****1973060000    否    是     1999年  2017     1.7    3.7    246
57    58  男  ****1987000000    否    否     2009年  2017     2.0    7.2    246
92    93  男  ****1990040000    否    否     2015年  2017     2.6    7.2    244
68    69  男  ****1958090000    否    否     1976年  2017     1.7    4.6    244
48    49  男  ****1971050000    否    否     2008年  2017     1.4    5.0    242
72    73  女  ****1985010000    否    否     2009年  2017     1.4    3.5    240
38    39  男  ****1989080000    否    否     2011年  2017     1.7    5.3    238
104  105  女  ****1982030000    否    否     2009年  2017     1.9    6.2    237
26    27  女  ****1981120000    否    否     2009年  2017     2.0    5.8    237
98    99  女  ****1988090000    否    否     2014年  2017     1.7    4.7    236
41    42  男  ****1992100000    否    否     2015年  2017     1.6    7.8    233
99   100  男  ****1983010000    否    否     2008年  2017     1.4    6.5    231
32    33  男  ****1993090000    是    否     2015年  2017     1.5    3.7    228
10    11  男  ****1982100000    否    否     2012年  2017     1.5    5.0    228
29    30  女  ****1984020000    否    否     2003年  2017     1.3    3.8    227
132  133  男  ****1973090000    否    否     1992年  2015     2.2    9.0    226
137  138  男  ****1990030000    否    否     2012年  2015     1.2    7.7    225
20    21  男  ****1979080000    否    否     2014年  2017     1.4    4.3    225
66    67  女  ****1991030000    否    否     2015年  2017     1.3    3.8    224
65    66  女  ****1985050000    否    否     2011年  2017     1.5    5.8    224
121  122  男  ****1975110000    否    否     2014年  2017     2.9    7.5    223
120  121  男  ****1975110000    否    否     2014年  2017     2.9    7.5    223
96    97  女  ****1968030000    否    否     2004年  2017     2.1    6.0    222
58    59  女  ****1983120000    否    否     2003年  2017     1.2    5.8    222
74    75  女  ****1982040000    否    否     2011年  2017     1.4    4.1    220
101  102  男  ****1950120000    否    否     1977年  2017

mean    max  median  min
性别                               
女    5.367308   10.1     5.1  3.5
男   10.221111  404.0     5.6  3.2

### 实验总结与心得体会

通过本次实验我们学习了对数据处理和分析的基本操作，包括数据读取、数据筛选、数据排序、数据分组和统计等。我们使用了 Python 编程语言和其常用数据处理和分析库 Pandas 进行实现。
在实验过程中，我们通过 Pandas 模块中的相关函数对 Excel 表格数据进行了加载和处理，并通过 Pandas 提供的函数和方法对数据进行了一系列操作，包括数据的基本描述、形状查看、列的读取、行列的提取、排序和分组统计等。
并且我们掌握了 Pandas 库的基本操作方法，可以有效地对大量的数据进行处理和分析，并可以根据需求进行数据的筛选、排序和统计等操作。这些基本技能是数据分析和挖掘工作的基础，对于研究数据和解决实际问题都具有重要的意义。

### 实验成绩：

________________________________